### ISSUE TITLE
atlbase.h missing overnight

### ISSUE THREAD

**Issue by sodul** [microsoft/setup-msbuild#127]
We have a CI pipeline that worked yesterday on a private repository that has had no commits in weeks.

As of about 16hs ago we now get:
```
fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory
```

Here is what our workflow file looks like:
```
name: CI
on:
  push:
    branches: [ 'main', 'releases/**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
  # Allow manual trigger for debugging the workflow.
jobs:
  CI-checks:
    runs-on: windows-2022
    steps:
      - name: Disable git autocrlf
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      # The msbuild version is dictated by the Windows image provided by GitHub.
      - uses: microsoft/setup-msbuild@v2
      - uses: darenm/Setup-VSTest@v1.2
      - name: Build and test with Sonar Wrapper
        shell: cmd
        run: test-all.cmd
```

Since there was no recent changes to our repository there must be some changes to the VisualStudio installation that made `altbase.h` no longer available when compiling.
