### ISSUE TITLE
My program is written in VS under Windows and uses GitHub. Why is the console output displaying garbled Chinese characters?

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/setup-msbuild#133]
My project's build option is Unicode, but the character set in the code is all ANSI, meaning char is used, not wchar_t. All the code files are saved as UTF-8 BOM. The same code can output Chinese characters correctly in the console on Ubuntu 22.04 and macOS 13. Why can't it display correctly on the Windows platform?

```

name: windows build workflows

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  
permissions:
  contents: read
  
jobs:
  build:
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        configuration: [Debug ,Release]
        platform: [x86 ,x64]

    runs-on: windows-latest

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4
        with:
          ref: 'develop'
        
      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine
          
      - name: sub module checkout (opensource)
        run: |
            git submodule init
            git submodule update
        shell: pwsh

      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg     
         
      - name: vcpkg install (x86)
        if: matrix.platform == 'x86'  
        run: |
            cd vcpkg
            ./bootstrap-vcpkg.bat
            ./vcpkg.exe install libsrt:x86-windows libsrtp:x86-windows
            ./vcpkg.exe integrate install
        shell: pwsh
      - name: vcpkg install (x64)
        if: matrix.platform == 'x64'  
        run: |
            cd vcpkg
            ./bootstrap-vcpkg.bat
            ./vcpkg.exe install libsrt:x64-windows libsrtp:x64-windows
            ./vcpkg.exe integrate install
        shell: pwsh

      - name: Set up Dependency Environment Variables
        run: |
          echo "XENGINE_INCLUDE=${{ github.workspace }}/libxengine" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "XENGINE_LIB32=${{ github.workspace }}/libxengine/XEngine_Windows/x86" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "XENGINE_LIB64=${{ github.workspace }}/libxengine/XEngine_Windows/x64" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild XEngine_Source/XEngine.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

      - name: Conditional Step for x86 Release
        if: matrix.configuration == 'Release' && matrix.platform == 'x86'
        run: |
          cp -r XEngine_Source/Release/*.dll XEngine_Release/
          cp -r XEngine_Source/Release/*.exe XEngine_Release/
          cp -r XEngine_Source/VSCopy_x86.bat XEngine_Release/
          cd XEngine_Release
          ./VSCopy_x86.bat
          ./XEngine_StreamMediaApp.exe -t        #printf garbled characters
        shell: pwsh

```
