### ISSUE TITLE
Error: Unable to resolve action `microsoft/setup-msbuild@2`, unable to find version `2`

### ISSUE THREAD

**Issue by DamianMorozov** [microsoft/setup-msbuild#136]
Hello. Thank you for your contribution to Open Source.
I am using msbuild in GitHub actions. As of recently, workflow started crashing in error. I updated the version msbuild and it started crashing with an error
```
Current runner version: '2.320.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `microsoft/setup-msbuild@2`, unable to find version `2`.
```

Here is a non-working .github/workflows/branch_main_build.yml
```
name: Branch Main Build

on:
  push:
    branches:
      - main
    paths:
      - '**.csproj'
      - '**.razor'
      - '**.cs'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@2
  
      - name: Setup Nuget Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Install dependencies
        run: nuget restore TgDownloader.sln

      - name: Build app for Release Any CPU
        run: msbuild TgDownloader.sln -t:rebuild -verbosity:quiet -property:Configuration=Release -property:Platform="Any CPU"
```

Here is my working .github/workflows/branch_main_build.yml
```
name: Branch Main Build

on:
  push:
    branches:
      - main
    paths:
      - '**.csproj'
      - '**.razor'
      - '**.cs'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2.0.0
  
      - name: Setup Nuget Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Install dependencies
        run: nuget restore TgDownloader.sln

      - name: Build app for Release Any CPU
        run: msbuild TgDownloader.sln -t:rebuild -verbosity:quiet -property:Configuration=Release -property:Platform="Any CPU"
```

The main difference is:
`uses: microsoft/setup-msbuild@v2` must to replace on `uses: microsoft/setup-msbuild@v2.0.0`

Please update the Readme documentation.
