### ISSUE TITLE
16.7 shows 16.8

### ISSUE THREAD

**Issue by johnkors** [microsoft/setup-msbuild#35]
Hi,

Am I doing it wrong, or is there any other way to get it to use 16.7? It seems to resolve 16.8 even though I specify 16.7.

```yml
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: 16.7
      - name: show msbuild version
        run: msbuild -version
```

Output:

```
Run msbuild -version
  msbuild -version
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
Microsoft (R) Build Engine version 16.8.1+bd2ea1e3c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.8.1.52902
```
