### ISSUE TITLE
MSBuild.exe is not in the Path

### ISSUE THREAD

**Issue by Max-ChenFei** [microsoft/setup-msbuild#48]
Hi, I just run a simple test for this action as follows:
```
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
```
Then I try to run msbuild, but the command was not found.
I suspect whether msbuild can be found via environment or not?

Here output the stepup-msbuild:
```
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products * -requires Microsoft.Component.MSBuild -property installationPath -latest
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
```
Actually the msbuild.exe should in  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild/Current/bin/
I use luchihoratiu/debug-via-ssh@main to connect to github runner and debug, run msbuild after setup-msbuild action, but msbuild was not recognized, which means the path was not added into the path.

What am I missing or misusage?
Thanks for the consideration
