### ISSUE TITLE
Error: Unable to find MSBuild.

### ISSUE THREAD

**Issue by cezarypiatek** [microsoft/setup-msbuild#50]
Here's my github action script:

```yml
name: pr-verification
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-extension:
    runs-on: windows-latest
    env: 
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        RepositoryUrl: 'https://github.com/${{ github.repository }}'
        RepositoryBranch: '${{ github.ref }}'
        SourceRevisionId: '${{ github.sha }}'
        VersionSuffix: 'pr-${{github.event.number}}.${{ github.run_number }}'
        Configuration: Release
        SolutionPath: Src\Tellurium.sln
    steps:
    - uses: actions/checkout@v2   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.8,16.9)'
```

Here's the output 

```plaintext
Run microsoft/setup-msbuild@v1.0.2
  with:
    vs-version: [16.8,16.9)
  env:
    DOTNET_NOLOGO: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    RepositoryUrl: https://github.com/cezarypiatek/Tellurium
    RepositoryBranch: refs/pull/76/merge
    SourceRevisionId: 7dd485291311cebe37c50611033a5befa3715129
    VersionSuffix: pr-76.3
    Configuration: Release
    SolutionPath: Src\Tellurium.sln
    DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
C:\ProgramData\Chocolatey\bin\vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest -version [16.8,16.9)
Error: Unable to find MSBuild.
```

Link to failed build https://github.com/cezarypiatek/Tellurium/pull/76/checks?check_run_id=2422153905

However, when I remove the version requirements  (` vs-version` parameter) then it works fine.
