### ISSUE TITLE
[Documentation] Add usage example of msbuild-architecture input

### ISSUE THREAD

**Issue by LanceMcCarthy** [microsoft/setup-msbuild#67]
Add description and examples of using the `msbuild-architecture` input.

For example:

```yaml
    - name: Setup 64 bit msbuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: 'x64'
```

and

```yaml
    - name: Setup 32 bit msbuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: 'x86'
```

> It would also be nice to see the other parameter descriptions/examples. If you're updating it for this one, might as well add any missing ones while you're in there :)
