### ISSUE TITLE
Unable to find msbuild.

### ISSUE THREAD

**Issue by Airn5475** [microsoft/setup-msbuild#7]
I am trying to run this action on a self-hosted runner.

```
- name: Add msbuild to PATH
  uses: microsoft/setup-msbuild@v1.0.0
    with:
      vs-version: 15.0
```

Here's the output:

> "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version 15 -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
> ##[error]Unable to find msbuild.

I tried doing the following, but it says it expects string, number, or boolean, not an array.
```
vs-version:
  [15.0,15.9]
```
I have Visual Studio Build tools installed on this server.
