### ISSUE TITLE
Setting vs-version: [17.0, 18.0) results in Error: Unable to find MSBuild.

### ISSUE THREAD

**Issue by CartBlanche** [microsoft/setup-msbuild#71]
As per subject, when I run....
```
Run microsoft/setup-msbuild@v1.1
  with:
    vs-version: [17.0, 18.0)
    msbuild-architecture: x64
  env:
    DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
    NUGET: C:\hostedtoolcache\windows\nuget.exe\5.11.0\x64/nuget.exe
```

and following error

```
C:\ProgramData\Chocolatey\bin\vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest -version "[17.0, 18.0)"
Error: Unable to find MSBuild.
```

When is VS2022 likely to be supported?
