### ISSUE TITLE
Using multiple include directories

### ISSUE THREAD

**Issue by Maticzpl** [microsoft/setup-msbuild#72]
Hello.
Im trying to build a project with some additional libraries from VCPKG
```
    - name: Add MSBuild to PATH
          uses: microsoft/setup-msbuild@v1.0.2      
      
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v10.0     
      with:       
        vcpkgGitCommitId: 5568f110b509a9fd90711978a7cb76bae75bb092
        vcpkgGitURL: https://github.com/microsoft/vcpkg.git
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgJsonGlob: '**/vcpkg.json'
        runVcpkgInstall: true
        
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration="${{ matrix.build }}" /p:IncludePath="${{env.VCPKG_ROOT}}\packages\glfw3_x64-windows\include\;${{env.VCPKG_ROOT}}\packages\glad_x64-windows\include\;${{env.VCPKG_ROOT}}\packages\glm_x64-windows\include\" ${{env.SOLUTION_FILE_PATH}}
```
For some reason the IncludePath property doesnt allow me to add multiple directories
I get this error:
`MSBUILD : error MSB1006: Property is not valid.
Switch: D:\a\GLWrapper\GLWrapper\vcpkg\packages\glad_x64-windows\include\`
The first include directory is fine but after the semicolon it breaks
