### ISSUE TITLE
How to use with visual studio old version (vs2013) 

### ISSUE THREAD

**Issue by teng-wu** [microsoft/setup-msbuild#76]
Hi, I am using the action for windows build. 
My sln only can be built by vs 2013.
I tried 
```
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
            vs-version: '12.0'
      - name: Build
        run: |
          @echo | msbuild -m myApplication.sln -p:PlatformToolset=v120 -p:Configuration=Release -p:Platform=Win32
```
But I got the following error:

 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(436,5): error MSB8020: The build tools for Visual Studio 2013 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install Visual Studio 2013 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution"

Looking for your reply.
