### ISSUE TITLE
Add support for ARM64

### ISSUE THREAD

**Issue by filipnavara** [microsoft/setup-msbuild#96]
With the VS ARM64 native support and Dev Kit machines available it would be nice to have native support for it.

**Comment by timheuer** [comment]
@filipnavara -- I just did some exploring with the underlying aspects that power setup-msbuild (vswhere) -- given that ARM64 support is prerelease you'd have to send that signal.  Have you done that and still not finding it?

so:
```
- name: Add msbuild to PATH
  uses: microsoft/setup-msbuild@v1
  with:
    vs-prerelease: true
```
